# -*- coding: utf-8 -*-
"""Data Visualization

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P3EeJ1sR-xvyfChq1sK4o0wDn_eEBWfE

##Python Assignments

## Data Visualization

1. In this assignment students have to transform iris data into 3 dimensions
and plot a 3d chart with transformed dimensions and colour each data
point with specific class.
"""

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from sklearn.datasets import load_iris

# Load the dataset
iris = load_iris()

# Using only 3 features 
X = iris.data[:, :3]
y = iris.target

fig = plt.figure(figsize=(8, 6))
ax = fig.add_subplot(111, projection='3d')
ax.set_title("Iris dataset in 3D")

for label in np.unique(y):
    ix = np.where(y == label)
    ax.scatter(X[ix, 0], X[ix, 1], X[ix, 2], label=iris.target_names[label])

# Add axis labels and legend
ax.set_xlabel(iris.feature_names[0])
ax.set_ylabel(iris.feature_names[1])
ax.set_zlabel(iris.feature_names[2])
ax.legend()

plt.show()

