# -*- coding: utf-8 -*-
"""Numpy Assignment

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P3EeJ1sR-xvyfChq1sK4o0wDn_eEBWfE

##Python Assignments

##NumPy Assignment

Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows:

The moving average sequence has n-k+1 elements as shown below.

1. Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.
"""

def moving_average(arr,window):
    n = len(arr)
    moving_avg = []
    for i in range(n-window+1):
        window_array = arr[i:i+window]
        window_sum = sum(window_array)
        moving_avg.append(window_sum/window)
    return moving_avg

array = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
moving_average(array, window=3)

