# -*- coding: utf-8 -*-
"""Strings, objects

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P3EeJ1sR-xvyfChq1sK4o0wDn_eEBWfE

##Python Assignments

### Strings, objects and list objects

1. Write a Python program to reverse a word after accepting the input from the user without using comments
"""

inp = input("Enter a word: ")
reversed_inp = inp[::-1]
print("The reversed word is:", reversed_inp)

"""2. Create the below pattern using nested for loop in Python.

"""

num_rows = 5

#First half
for i in range(1, num_rows + 1):
    print("*" * i)

# Second half 
for i in range(num_rows - 1, 0, -1):
    print("*" * i)

